# fly.toml file for a Discord Bot using Dockerfile

app = "discord-bot-summer-sun-7175"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"


[env]
  # Discord BotはHTTPサーバーでないのでPORT不要。ただし入っていても害はありません。
  # PORT = "8080"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Discord Bot は HTTP アクセスを受けないので [http_service] セクションも削除
# もし今後 Flask 等を使う場合は復活させる

# Machines設定（optional。自動起動停止する設定を維持）
[experimental]
  auto_rollback = true
