app = "discord-bot-summer-sun-7175"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"  # Dockerfileを使ったビルド

[http_service]
  auto_stop_machines = "stop"       # ✅ 未使用時は自動停止
  auto_start_machines = true        # ✅ リクエストが来たら自動起動
  min_machines_running = 0          # ✅ 常時起動しない（無料枠節約）
  internal_port = 8080              # PORTがあるなら指定（Flask用など）

[[vm]]
  memory = "256mb"                  # ✅ 最小メモリ（無料枠最大活用）
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8080"                     # Flaskなど使ってる場合は必要