services:
  - type: worker
    name: discord-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        value: ${DISCORD_TOKEN}
